### ISSUE TITLE
How to run this?

### ISSUE THREAD

**Issue by M4GNV5** [davidrlunu/dots-and-dashes#6]
It would be cool if you could add an `Installing` section to the readme so noobs like me can use it.

**Comment by M4GNV5** [comment]
ohh wait i found this :laughing: https://www.reddit.com/r/unixporn/comments/4rgcdq/openbox_i_herd_you_like_rice/d517sdi

**Comment by M4GNV5** [comment]
My current problem is:

``` sh
$ pwd
/home/jakob

$ export USER=jakob

$ conky -c .conky/conky.conf
Conky: llua_load: cannot open /home/$USER/.conky/system_clock.lua: No such file or directory
Conky: desktop window (1200016) is subwindow of root window (1eb)
Conky: window type - normal
Conky: drawing to created window (0x2400002)
Conky: drawing to double buffer
Conky: llua_do_call: function conky_main execution failed: attempt to call a nil value
Conky: llua_do_call: function conky_main execution failed: attempt to call a nil value
[...]
Conky: llua_do_call: function conky_main execution failed: attempt to call a nil value
Conky: llua_do_call: function conky_main execution failed: attempt to call a nil value
^CConky: received SIGINT or SIGTERM to terminate. bye!

```

**Comment by davidrlunu** [comment]
This is really strange.
Try to open a terminal and see what "echo $USER" gives you and also try a quick "ls /home/$USER/" to see if it works.
What distro are you using?

**Comment by M4GNV5** [comment]
Im using debian 8.5

```
$ uname -a
Linux magnus 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
```

I also managed to replace `/home/$USER` in every file with `~` and it actually starts now (without any error messages) but it only displays the blue circle in the middle, no cpu/gpu stats, weather, calender etc. screenshot: https://i.m4gnus.de/3weia0.png

also: `echo $USER` gives me `jakob`

``` sh
$ ls /home/$USER/.conky

asset.png          conky_cpus       conky_weather    sensors.lua
binarclock.py      conky_gmail      connections.png  system_clock.lua
calendar           conky_hdd        cpu_rings.lua    templeterino.conf
conky_asset        conky_loggs      dbus-mon.py      weather
conky_biclock      conky_notifs     Mail.png         whatsapp_proc_check.sh
conky_cal          conky_processes  mail.py
conky.conf         conky_sensors    Notifs.png
conky_connections  conky_stod       processes.png
```

**Comment by davidrlunu** [comment]
Hehe : ) 
Mate, you have to chain load every conky file! 
Open a terminal and issue  "for x in /home/$USER/.conky/conky_*: do conky -c x: done;" 

Or just manually try to load them to see if you get errors or anything: "conky -c /path/file" 

Beware that CPU/GPU sensors might take a few seconds to initialize and the "conky_asset" as well, because it needs to do the speed test.

**Comment by M4GNV5** [comment]
Ahh, nice.
New problems have arisen though: I assume you are using conky 1.10+ ? because according to http://askubuntu.com/questions/788228/conky-does-not-use-instructed-font-with-cant-load-xft-font-error the config syntax changed and for me conky (v1.9.0) complains that it cannot load `templeterino.conf`

so when running e.g. conky_cpus i get this:

``` sh
$ conky -c conky_cpus

Conky: Can't load configfile '~/.conky/templeterino.conf'.
Conky: desktop window (1200016) is subwindow of root window (1eb)
Conky: drawing to desktop window
Conky: drawing to single buffer
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  55 (X_CreateGC)
  Serial number of failed request:  99
  Current serial number in output stream:  101
```

EDIT: hmm according to https://github.com/brndnmtthws/conky/wiki/Convert-to-new-1.10-syntax your config files appear to be for 1.9, (because of the #comments) any idea why it cannot load the config file? is there a way to get a useful error message out of conky?

**Comment by davidrlunu** [comment]
There are two versions of the HUD on the repo, mate. 
conky_OPSAT and conky_OPSAT_v1.10. in the 1.10 version there is no templaterino.conf file.

**Comment by ivanbrennan** [comment]
Does `conky_biclock` require python 3.4 (rather than, say 3.5)? When I try to run it, I get an error that makes me think I'd need to install 3.4 to get it working. I have 3.5, and it looks like installing 3.4 would be a pretty involved process, so thought I'd check first if there's another way around this.
```
$ conky -c ~/.conky/conky_biclock
conky: desktop window (800015) is subwindow of root window (10a)
conky: window type - normal
conky: drawing to created window (0x4600002)
conky: drawing to double buffer
/home/ivan/.conky/biclock: error while loading shared libraries: libpython3.4.so.1.0: cannot open shared object file: No such file or directory
```
