### ISSUE TITLE
How do you get quark.gif to show?

### ISSUE THREAD

**Issue by popey456963** [davidrlunu/dots-and-dashes#9]

**Comment by davidrlunu** [comment]
I thought you can pretty much grasp that from the description, mate. It's a bash script called ".gifbg" 
Please read it and understand how it works.

**Comment by popey456963** [comment]
Ah, god damnit, I'm an idiot.

I use Refined Github which hides some stuff from the repository, .gifbg was one of them.

Apologies for wasting your time :(
